name: phaser
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - aiohttp
    - matplotlib
    - neutone_sdk @ git+https://github.com/Neutone/neutone_sdk.git@c69108d6ad11910afdc3ce4ead0a647456e2addb
    - pip-chill
    - plotly
    - pytorch-lightning
    - soundfile
    - torchaudio
    - torchlpc
    - torchvision==0.16.2
    - wandb
